# Conexiune �n memorie (se reseteaz? la fiecare restart)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Set?ri Hibernate pentru H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Consola H2 (po?i vedea tabelele �n browser la http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console